name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Apple Certificate
      run: |
        echo "${{ secrets.CERT_PASSWORD }}" | base64 --decode > /tmp/CERT_PASSWORD.txt
        echo "${{ secrets.APPLE_CERT }}" | base64 --decode > /tmp/APPLE_CERT.p12
        security create-keychain -p "temp-password" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "temp-password" build.keychain
        security import /tmp/apple_cert.p12 -k ~/Library/Keychains/build.keychain -P $(cat /tmp/cert_password.txt) -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k "temp-password" build.keychain
      env:
        CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        APPLE_CERT: ${{ secrets.APPLE_CERT }}
    - name: Build the Project
      run: xcodebuild -project MacAudioConverter.xcodeproj -scheme MacAudioConverter -sdk macosx
